[package]
name = "dead-ringer"
version = "1.0.1"
edition = "2021"
description = "Dring, A Binary Diff Utility"
authors = ["Zackary Troop"]

[[bin]]
name = "dring"
path = "src/main.rs"

[dependencies]
tui = { version = "0.19.0", features = ["crossterm"] }
crossterm = "0.27"